language: shell

script:
  - git remote rm origin
  - git remote add origin https://github.com/travis-ci/dpl.git
  - git fetch origin master
  - git branch -v -a
  - git checkout -b master origin/master
  - .travis/trigger -t $TRAVIS_API_TOKEN_2 -b master
  - sleep 3
